import type { Metadata } from "next";
import { ServicePage } from "@/components/service-page";

export const metadata: Metadata = { title: "Cyber Drill Exercise", description: "Uji kesiapan teknis organisasi melalui simulasi serangan siber yang realistis dan terukur." };

export default function CyberDrillPage() {
  return <ServicePage content={{
    id: {
      eyebrow: "Cyber Drill Exercise",
      title: "Simulate. Respond.",
      accent: "Improve.",
      summary: "Simulasi serangan siber dari sisi teknis yang dirancang untuk menguji kemampuan organisasi dalam mendeteksi, merespons, dan menangani insiden keamanan secara nyata.",
      image: "/images/cyber-drill-hero.png",
      imageLight: "/images/Solusi_Cyberdrill_Light.png",
      imageAlt: "Simulasi serangan siber CyberXatria",
      aboutEyebrow: "Tentang layanan",
      aboutTitle: "Apa itu Cyber Drill?",
      about: ["Cyber Drill adalah latihan simulasi serangan siber yang dirancang untuk menguji kesiapan organisasi dalam mendeteksi, merespons, dan menangani serangan siber.", "Skenario yang menyerupai kondisi nyata membantu organisasi menemukan kelemahan pada proses, teknologi, koordinasi, dan kemampuan tim sebelum menghadapi insiden sebenarnya."],
      pillars: ["Deteksi", "Respons", "Perbaikan"],
      challengesEyebrow: "Risiko operasional",
      challengesTitle: "Tantangan yang Kami Bantu Atasi",
      challengesText: "Kami membantu tim melihat risiko lebih dini dan memperkuat koordinasi sebelum dampaknya meluas.",
      challenges: [
        { icon: "Gauge", title: "Kesiapan Belum Terukur", text: "Organisasi belum mengetahui seberapa siap menghadapi serangan nyata." },
        { icon: "Crosshair", title: "Minim Pengalaman", text: "Tim belum terbiasa menangani serangan dalam lingkungan terkontrol." },
        { icon: "Workflow", title: "Prosedur Belum Teruji", text: "Incident response plan belum pernah diuji dari awal hingga akhir." },
      ],
      featuresEyebrow: "Kapabilitas",
      featuresTitle: "Layanan & Fitur Utama",
      features: [
        { icon: "Crosshair", title: "Simulated Attack Scenario", text: "Simulasi serangan berdasarkan skenario yang telah ditentukan." },
        { icon: "ShieldCheck", title: "Blue Team Validation", text: "Menguji kemampuan tim dalam mendeteksi dan merespons serangan." },
        { icon: "Radar", title: "Gap Assessment", text: "Mengidentifikasi kesenjangan pada proses, teknologi, dan kemampuan tim." },
      ],
      flowEyebrow: "Alur terukur",
      flowTitle: "Bagaimana Prosesnya Bekerja",
      flow: ["Identifikasi", "Deteksi", "Respons", "Pengendalian", "Pemulihan", "Evaluasi", "Peningkatan"],
      flowImages: ["/images/Identifikasi.png", "/images/Deteksi.png", "/images/Response.png", "/images/Pengendalian.png", "/images/Pemulihan.png", "/images/Evaluasi.png", "/images/Peningkatan.png"],
      packagesEyebrow: "Pilihan layanan",
      packagesTitle: "Service Packages",
      packagesText: "Pilih paket awal yang paling sesuai. Hubungi tim kami untuk detail komersial dan ruang lingkup layanan.",
      recommended: "Direkomendasikan",
      packages: [
        { name: "Regular Scenario", description: "Skenario terstruktur untuk mengukur kesiapan dasar tim pertahanan.", items: ["Skenario serangan standar", "Latihan Blue Team", "Penilaian kemampuan deteksi", "Skor kesiapan", "Laporan latihan"] },
        { name: "Cyber Drill Advanced", description: "Skenario serangan lanjutan dengan evaluasi Red & Blue Team.", featured: true, items: ["Skenario serangan lanjutan", "Red & Blue Team", "Penilaian deteksi dan respons", "Evaluasi kinerja", "Laporan terperinci"] },
        { name: "Customized Scenario", description: "Skenario, jalur serangan, dan lingkup latihan disesuaikan dengan kebutuhan.", items: ["Skenario yang disesuaikan", "Jalur serangan yang disesuaikan", "Latihan lintas tim", "Penilaian komprehensif", "Rekomendasi perbaikan"] },
      ],
      audienceEyebrow: "Cocok untuk siapa?",
      audienceTitle: "Dibangun untuk Organisasi yang Serius dengan Kesiapan Siber",
      audience: ["IT & Security Team", "SOC / CSIRT", "Blue Team", "Incident Response Team"],
      benefits: [
        { icon: "Gauge", title: "Ukur Kesiapan", text: "Dapatkan benchmark readiness berbasis performa selama latihan." },
        { icon: "ScanSearch", title: "Temukan Gap", text: "Identifikasi kelemahan pada people, process, dan technology." },
        { icon: "Timer", title: "Percepat Respons", text: "Latih tim mengambil tindakan yang tepat dalam waktu terbatas." },
      ],
      ctaEyebrow: "Langkah berikutnya",
      ctaTitle: "Uji kesiapan organisasi Anda sebelum penyerang sebenarnya melakukannya.",
      ctaButton: "Request Consultation",
    },
    en: {
      eyebrow: "Cyber Drill Exercise",
      title: "Simulate. Respond.",
      accent: "Improve.",
      summary: "A technical cyberattack simulation designed to test an organization's ability to detect, respond to, and handle real-world security incidents.",
      image: "/images/cyber-drill-hero.png",
      imageLight: "/images/Solusi_Cyberdrill_Light.png",
      imageAlt: "CyberXatria cyberattack simulation",
      aboutEyebrow: "About the service",
      aboutTitle: "What is Cyber Drill?",
      about: ["Cyber Drill is a cyberattack simulation exercise designed to test an organization's readiness to detect, respond to, and handle cyberattacks.", "Realistic scenarios help organizations find weaknesses in process, technology, coordination, and team capability before facing a real incident."],
      pillars: ["Detection", "Response", "Improvement"],
      challengesEyebrow: "Operational risk",
      challengesTitle: "Challenges We Help Address",
      challengesText: "We help teams see risk earlier and strengthen coordination before impact expands.",
      challenges: [
        { icon: "Gauge", title: "Readiness Is Not Measured", text: "Organizations may not know how ready they are to face real attacks." },
        { icon: "Crosshair", title: "Limited Experience", text: "Teams are not used to handling attacks in a controlled environment." },
        { icon: "Workflow", title: "Untested Procedures", text: "The incident response plan has not been tested end to end." },
      ],
      featuresEyebrow: "Capabilities",
      featuresTitle: "Core Services & Features",
      features: [
        { icon: "Crosshair", title: "Simulated Attack Scenario", text: "Attack simulation based on a defined scenario." },
        { icon: "ShieldCheck", title: "Blue Team Validation", text: "Testing team capability to detect and respond to attacks." },
        { icon: "Radar", title: "Gap Assessment", text: "Identifying gaps in process, technology, and team capability." },
      ],
      flowEyebrow: "Measured flow",
      flowTitle: "How the Process Works",
      flow: ["Identify", "Detect", "Respond", "Contain", "Recover", "Evaluate", "Improve"],
      flowImages: ["/images/Identifikasi.png", "/images/Deteksi.png", "/images/Response.png", "/images/Pengendalian.png", "/images/Pemulihan.png", "/images/Evaluasi.png", "/images/Peningkatan.png"],
      packagesEyebrow: "Service options",
      packagesTitle: "Service Packages",
      packagesText: "Choose the most suitable starting package. Contact our team for commercial details and service scope.",
      recommended: "Recommended",
      packages: [
        { name: "Regular Scenario", description: "Structured scenario to measure basic defense team readiness.", items: ["Standard attack scenario", "Blue Team exercise", "Detection assessment", "Readiness score", "Exercise report"] },
        { name: "Cyber Drill Advanced", description: "Advanced attack scenario with Red & Blue Team evaluation.", featured: true, items: ["Advanced attack scenario", "Red & Blue Team", "Detection & response assessment", "Performance evaluation", "Detailed report"] },
        { name: "Customized Scenario", description: "Scenario, attack path, and exercise scope tailored to needs.", items: ["Customized scenario", "Customized attack path", "Cross-team exercise", "Comprehensive assessment", "Improvement recommendation"] },
      ],
      audienceEyebrow: "Who is it for?",
      audienceTitle: "Built for Organizations Serious About Cyber Readiness",
      audience: ["IT & Security Team", "SOC / CSIRT", "Blue Team", "Incident Response Team"],
      benefits: [
        { icon: "Gauge", title: "Measure Readiness", text: "Get a performance-based readiness benchmark from the exercise." },
        { icon: "ScanSearch", title: "Find Gaps", text: "Identify weaknesses in people, process, and technology." },
        { icon: "Timer", title: "Accelerate Response", text: "Train teams to take the right actions under time pressure." },
      ],
      ctaEyebrow: "Next step",
      ctaTitle: "Test your organization's readiness before real attackers do.",
      ctaButton: "Request Consultation",
    },
  }} />;
}
