import type { Metadata } from "next";
import { ServicePage } from "@/components/service-page";

export const metadata: Metadata = { title: "Cyber Drill Exercise", description: "Uji kesiapan teknis organisasi melalui simulasi serangan siber yang realistis dan terukur." };

export default function CyberDrillPage() {
  return <ServicePage content={{
    id: {
      eyebrow: "Cyber Drill Exercise",
      title: "Simulasi. Respon.",
      accent: "Peningkatan.",
      summary: "Uji kemampuan organisasi dalam menghadapi serangan siber melalui simulasi serangan yang realistis dan terukur.",
      image: "/images/cyber-drill-hero.png",
      imageLight: "/images/Solusi_Cyberdrill_Light.png",
      imageAlt: "Simulasi serangan siber CyberXatria",
      aboutEyebrow: "Tentang layanan",
      aboutTitle: "Apa itu Cyber Drill?",
      about: ["Cyber Drill adalah latihan simulasi serangan siber yang dirancang untuk menguji kesiapan organisasi dalam mendeteksi, merespons, dan menangani serangan siber.", "Skenario yang menyerupai kondisi nyata membantu organisasi menemukan kelemahan pada proses, teknologi, koordinasi, dan kemampuan tim sebelum menghadapi insiden sebenarnya."],
      pillars: ["Deteksi", "Respons", "Perbaikan"],
      challengesEyebrow: "Risiko operasional",
      challengesTitle: "Tantangan yang Kami Bantu Atasi",
      challengesText: "Kami membantu tim melihat risiko lebih dini dan memperkuat koordinasi sebelum dampaknya meluas.",
      challenges: [
        { icon: "Gauge", title: "Kesiapan Belum Terukur", text: "Belum mengetahui seberapa siap menghadapi serangan siber." },
        { icon: "Siren", title: "Belum Terbiasa Serangan Nyata", text: "Tim belum terbiasa menangani serangan nyata." },
        { icon: "Workflow", title: "Prosedur Belum Teruji", text: "Prosedur incident response belum pernah diuji." },
        { icon: "UsersRound", title: "Koordinasi Belum Optimal", text: "Koordinasi antar tim belum optimal." },
        { icon: "Radar", title: "Gap Detection & Response", text: "Tidak mengetahui gap kemampuan detection & response." },
        { icon: "Timer", title: "Efektivitas Respons Sulit Diukur", text: "Sulit mengukur efektivitas respons terhadap serangan." },
      ],
      featuresEyebrow: "Kapabilitas",
      featuresTitle: "Layanan & Fitur Utama",
      features: [
        { icon: "Crosshair", title: "Attack Simulation", text: "Simulasi serangan untuk menguji kesiapan tim menghadapi skenario nyata." },
        { icon: "ShieldCheck", title: "Blue Team Exercise", text: "Latihan untuk menguji deteksi, analisis, dan respons tim pertahanan." },
        { icon: "Siren", title: "Red Team Simulation", text: "Simulasi taktik penyerang untuk menguji kontrol dan kesiapan organisasi." },
        { icon: "Workflow", title: "Scenario-Based Exercise (Custom)", text: "Skenario latihan disesuaikan dengan kebutuhan, industri, dan profil risiko." },
        { icon: "Gauge", title: "Performance Assessment", text: "Penilaian performa tim berdasarkan tindakan dan keputusan selama latihan." },
        { icon: "FileCheck2", title: "Post-Exercise Report", text: "Laporan pascalatihan berisi temuan, evaluasi, dan rekomendasi perbaikan." },
      ],
      flowEyebrow: "Alur terukur",
      flowTitle: "Bagaimana Prosesnya Bekerja",
      flow: ["Identify", "Detect", "Respond", "Contain", "Recover", "Evaluate"],
      flowImages: ["/images/Identifikasi.png", "/images/Deteksi.png", "/images/Response.png", "/images/Pengendalian.png", "/images/Pemulihan.png", "/images/Evaluasi.png"],
      assessmentEyebrow: "Lingkup penilaian",
      assessmentTitle: "Area yang Dinilai",
      assessment: [
        { icon: "Eye", title: "Kemampuan mendeteksi ancaman", text: "" },
        { icon: "Siren", title: "Kemampuan merespons insiden", text: "" },
        { icon: "RotateCcw", title: "Kemampuan membatasi dampak dan memulihkan kondisi", text: "" },
        { icon: "UsersRound", title: "Koordinasi antar tim", text: "" },
        { icon: "Workflow", title: "Efektivitas prosedur penanganan insiden", text: "" },
        { icon: "Timer", title: "Kecepatan dalam mengambil tindakan", text: "" },
      ],
      deliverablesEyebrow: "Hasil kerja",
      deliverablesTitle: "Output yang Diterima",
      deliverables: [
        { icon: "FileCheck2", title: "Laporan Hasil Latihan", text: "" },
        { icon: "Gauge", title: "Penilaian Kinerja", text: "" },
        { icon: "ScanSearch", title: "Temuan & Gap Analisis", text: "" },
        { icon: "ClipboardCheck", title: "Evaluasi Tanggapan", text: "" },
        { icon: "RotateCcw", title: "Rekomendasi Perbaikan", text: "" },
      ],
      packagesEyebrow: "Pilihan layanan",
      packagesTitle: "Service Packages",
      packagesText: "Pilih paket awal yang paling sesuai. Hubungi tim kami untuk detail komersial dan ruang lingkup layanan.",
      recommended: "Direkomendasikan",
      packages: [
        { name: "Regular Scenario", description: "Skenario terstruktur untuk mengukur kesiapan dasar tim pertahanan.", items: ["Skenario serangan standar", "Latihan Blue Team", "Penilaian kemampuan deteksi", "Skor kesiapan", "Laporan latihan"] },
        { name: "Cyber Drill Advanced", description: "Skenario serangan lanjutan dengan evaluasi Red & Blue Team.", featured: true, items: ["Skenario serangan lanjutan", "Red & Blue Team", "Penilaian deteksi dan respons", "Evaluasi kinerja", "Laporan terperinci"] },
        { name: "Customized Scenario", description: "Skenario, jalur serangan, dan lingkup latihan disesuaikan dengan kebutuhan.", items: ["Skenario yang disesuaikan", "Jalur serangan yang disesuaikan", "Latihan lintas tim", "Penilaian komprehensif", "Rekomendasi perbaikan"] },
      ],
      audienceEyebrow: "Cocok untuk siapa?",
      audienceTitle: "Dibangun untuk Organisasi yang Serius dengan Kesiapan Siber",
      audience: ["IT & Security Team", "SOC / CSIRT", "Blue Team", "Incident Response Team"],
      benefits: [
        { icon: "Gauge", title: "Ukur Kesiapan", text: "Dapatkan benchmark readiness berbasis performa selama latihan." },
        { icon: "ScanSearch", title: "Temukan Gap", text: "Identifikasi kelemahan pada people, process, dan technology." },
        { icon: "Timer", title: "Percepat Respons", text: "Latih tim mengambil tindakan yang tepat dalam waktu terbatas." },
      ],
      ctaEyebrow: "Langkah berikutnya",
      ctaTitle: "Uji kesiapan organisasi Anda sebelum penyerang sebenarnya melakukannya.",
      ctaButton: "Request Consultation",
    },
    en: {
      eyebrow: "Cyber Drill Exercise",
      title: "Simulate. Respond.",
      accent: "Improve.",
      summary: "Test your organizations ability to respond to cyberattacks through realistic and measurable attack simulations.",
      image: "/images/cyber-drill-hero.png",
      imageLight: "/images/Solusi_Cyberdrill_Light.png",
      imageAlt: "CyberXatria cyberattack simulation",
      aboutEyebrow: "About the service",
      aboutTitle: "What is Cyber Drill?",
      about: ["Cyber Drill is a cyberattack simulation exercise designed to test an organization's readiness to detect, respond to, and handle cyberattacks.", "Realistic scenarios help organizations find weaknesses in process, technology, coordination, and team capability before facing a real incident."],
      pillars: ["Detection", "Response", "Improvement"],
      challengesEyebrow: "Operational risk",
      challengesTitle: "Challenges We Help Address",
      challengesText: "We help teams see risk earlier and strengthen coordination before impact expands.",
      challenges: [
        { icon: "Gauge", title: "Readiness Is Not Measured", text: "Organizations do not yet know how ready they are to face cyberattacks." },
        { icon: "Siren", title: "Limited Real-Attack Experience", text: "Teams are not yet used to handling real attacks." },
        { icon: "Workflow", title: "Untested Incident Response", text: "Incident response procedures have not been tested." },
        { icon: "UsersRound", title: "Cross-Team Coordination Gaps", text: "Coordination between teams is not yet optimal." },
        { icon: "Radar", title: "Unknown Detection & Response Gaps", text: "Detection and response capability gaps are not yet known." },
        { icon: "Timer", title: "Response Effectiveness Is Hard to Measure", text: "It is difficult to measure response effectiveness against attacks." },
      ],
      featuresEyebrow: "Capabilities",
      featuresTitle: "Core Services & Features",
      features: [
        { icon: "Crosshair", title: "Attack Simulation", text: "Attack simulations to test team readiness against realistic scenarios." },
        { icon: "ShieldCheck", title: "Blue Team Exercise", text: "Exercises to test detection, analysis, and defensive response." },
        { icon: "Siren", title: "Red Team Simulation", text: "Attacker-tactic simulations to test controls and organizational readiness." },
        { icon: "Workflow", title: "Scenario-Based Exercise (Custom)", text: "Exercise scenarios tailored to needs, industry, and risk profile." },
        { icon: "Gauge", title: "Performance Assessment", text: "Team performance assessment based on actions and decisions during the exercise." },
        { icon: "FileCheck2", title: "Post-Exercise Report", text: "Post-exercise report covering findings, evaluation, and improvement recommendations." },
      ],
      flowEyebrow: "Measured flow",
      flowTitle: "How the Process Works",
      flow: ["Identify", "Detect", "Respond", "Contain", "Recover", "Evaluate"],
      flowImages: ["/images/Identifikasi.png", "/images/Deteksi.png", "/images/Response.png", "/images/Pengendalian.png", "/images/Pemulihan.png", "/images/Evaluasi.png"],
      assessmentEyebrow: "Assessment scope",
      assessmentTitle: "Areas We Assess",
      assessment: [
        { icon: "Eye", title: "Threat detection capability", text: "" },
        { icon: "Siren", title: "Incident response capability", text: "" },
        { icon: "RotateCcw", title: "Impact containment and recovery capability", text: "" },
        { icon: "UsersRound", title: "Cross-team coordination", text: "" },
        { icon: "Workflow", title: "Incident handling procedure effectiveness", text: "" },
        { icon: "Timer", title: "Speed in taking action", text: "" },
      ],
      deliverablesEyebrow: "Deliverables",
      deliverablesTitle: "Outputs You Receive",
      deliverables: [
        { icon: "FileCheck2", title: "Exercise Result Report", text: "" },
        { icon: "Gauge", title: "Performance Assessment", text: "" },
        { icon: "ScanSearch", title: "Findings & Gap Analysis", text: "" },
        { icon: "ClipboardCheck", title: "Response Evaluation", text: "" },
        { icon: "RotateCcw", title: "Improvement Recommendations", text: "" },
      ],
      packagesEyebrow: "Service options",
      packagesTitle: "Service Packages",
      packagesText: "Choose the most suitable starting package. Contact our team for commercial details and service scope.",
      recommended: "Recommended",
      packages: [
        { name: "Regular Scenario", description: "Structured scenario to measure basic defense team readiness.", items: ["Standard attack scenario", "Blue Team exercise", "Detection assessment", "Readiness score", "Exercise report"] },
        { name: "Cyber Drill Advanced", description: "Advanced attack scenario with Red & Blue Team evaluation.", featured: true, items: ["Advanced attack scenario", "Red & Blue Team", "Detection & response assessment", "Performance evaluation", "Detailed report"] },
        { name: "Customized Scenario", description: "Scenario, attack path, and exercise scope tailored to needs.", items: ["Customized scenario", "Customized attack path", "Cross-team exercise", "Comprehensive assessment", "Improvement recommendation"] },
      ],
      audienceEyebrow: "Who is it for?",
      audienceTitle: "Built for Organizations Serious About Cyber Readiness",
      audience: ["IT & Security Team", "SOC / CSIRT", "Blue Team", "Incident Response Team"],
      benefits: [
        { icon: "Gauge", title: "Measure Readiness", text: "Get a performance-based readiness benchmark from the exercise." },
        { icon: "ScanSearch", title: "Find Gaps", text: "Identify weaknesses in people, process, and technology." },
        { icon: "Timer", title: "Accelerate Response", text: "Train teams to take the right actions under time pressure." },
      ],
      ctaEyebrow: "Next step",
      ctaTitle: "Test your organization's readiness before real attackers do.",
      ctaButton: "Request Consultation",
    },
  }} />;
}
