import type { Metadata } from "next";
import { ServicePage } from "@/components/service-page";

export const metadata: Metadata = { title: "Tabletop Exercise", description: "Simulasi krisis siber untuk menguji keputusan eksekutif, koordinasi, dan kesiapan organisasi." };

export default function TabletopPage() {
  return <ServicePage content={{
    id: {
      eyebrow: "Tabletop Exercise",
      title: "Uji Kesiapan Anda Sebelum",
      accent: "Insiden Siber Sebenarnya Terjadi",
      summary: "Tabletop Exercise adalah simulasi berbasis skenario yang membantu organisasi menguji kesiapan, koordinasi, dan pengambilan keputusan dalam menghadapi insiden keamanan siber.",
      image: "/images/tabletop-hero.png",
      imageLight: "/images/Solusi_TTX_Light.png",
      imageAlt: "Simulasi krisis siber untuk eksekutif",
      heroCtaButton: "Ajukan Tabletop Exercise",
      heroHighlights: [
        { label: "Berbasis Skenario", image: "/images/ttx 1.png" },
        { label: "Difasilitasi Ahli", image: "/images/ttx 2.png" },
        { label: "Penilaian yang Dapat Ditindaklanjuti", image: "/images/ttx 3.png" },
      ],
      aboutEyebrow: "TENTANG LAYANAN",
      aboutTitle: "Apa itu Tabletop Exercise?",
      about: [
        "Tabletop Exercise adalah simulasi diskusi terstruktur yang dirancang untuk menguji bagaimana organisasi merespons sebuah insiden keamanan siber.",
        "Peserta diberikan skenario insiden secara bertahap dan diminta untuk mendiskusikan tindakan, keputusan, komunikasi, serta koordinasi yang harus dilakukan pada setiap tahap insiden.",
        "Berbeda dengan simulasi teknis, Tabletop Exercise berfokus pada people, process, decision-making, and coordination sehingga organisasi dapat mengetahui apakah prosedur respons yang dimiliki sudah efektif dan siap digunakan ketika insiden benar-benar terjadi.",
      ],
      pillarLabel: "Simulasi · Diskusi · Penilaian · Peningkatan",
      pillars: ["Simulasi", "Diskusi", "Penilaian", "Peningkatan"],
      pillarImages: [
        "/images/ttx tentanglayanan1.png",
        "/images/ttx tentanglayanan2.png",
        "/images/ttx tentanglayanan3.png",
        "/images/ttx tentanglayanan4.png",
      ],
      challengesEyebrow: "MANFAAT UTAMA",
      challengesTitle: "Kenapa Melakukan Tabletop Exercise?",
      challengesText: "Wujudkan kesiapan nyata dari rencana tanggap insiden Anda.",
      challenges: [
        { icon: "BookOpenCheck", title: "Memvalidasi Rencana Respon Insiden", text: "Memastikan Incident Response Plan dan prosedur yang dimiliki dapat diterapkan secara efektif dalam kondisi insiden." },
        { icon: "Gavel", title: "Peningkatan Pengambil Keputusan", text: "Melatih stakeholder dalam mengambil keputusan secara cepat dan tepat ketika menghadapi situasi yang penuh tekanan." },
        { icon: "Network", title: "Memperkuat Koordinasi Antar-Tim", text: "Menguji koordinasi antara tim security, IT, management, legal, communication, dan business unit terkait." },
        { icon: "ScanSearch", title: "Mengidentifikasi Kesenjangan & Kelemahan", text: "Mengidentifikasi gap pada proses, komunikasi, escalation path, maupun pembagian tanggung jawab." },
        { icon: "ShieldCheck", title: "Meningkatkan Ketahanan Siber", text: "Meningkatkan kemampuan organisasi untuk merespons, mengendalikan, dan memulihkan diri dari insiden keamanan siber." },
        { icon: "UsersRound", title: "Meningkatkan Kesadaran Organisasi", text: "Meningkatkan pemahaman stakeholder mengenai peran dan tanggung jawab masing-masing selama terjadi cyber incident." },
      ],
      challengeIconImages: [
        "/images/TTX Validasi 1.png",
        "/images/TTX Keputusan 2.png",
        "/images/TTX Koordinasi 3.png",
        "/images/TTX Kesenjangan 4.png",
        "/images/TTX Ketahanan 5.png",
        "/images/TTX Kesadaran 6.png",
      ],
      featuresEyebrow: "",
      featuresTitle: "",
      features: [],
      flowEyebrow: "PROSES PELAKSANAAN",
      flowTitle: "Bagaimana Tabletop Exercise Dilaksanakan",
      flowText: "Dari persiapan skenario hingga pelaksanaan peningkatan.",
      flow: ["Persiapan", "Desain Skenario", "Briefing / Persiapan Peserta", "Simulasi Tabletop", "Penilaian", "Evaluasi dan Peningkatan"],
      flowDescriptions: [
        "Kami memahami kebutuhan, profil risiko, environment, dan objective organisasi untuk menentukan exercise yang relevan.",
        "Skenario dikembangkan berdasarkan kebutuhan organisasi, threat landscape, dan potensi cyber incident yang relevan.",
        "Peserta mendapatkan briefing mengenai tujuan, aturan, peran, dan konteks skenario sebelum exercise dimulai.",
        "Fasilitator memberikan scenario inject secara bertahap. Peserta kemudian mendiskusikan respons, keputusan, komunikasi, dan eskalasi yang harus dilakukan.",
        "Tim fasilitator melakukan observasi dan assessment terhadap hasil simulasi dan respons peserta.",
        "Hasil exercise dianalisis untuk menemukan gap dan improvement opportunity yang dapat digunakan sebagai dasar peningkatan cyber readiness.",
      ],
      flowImages: [
        "/images/TTX Persiapan 1.png",
        "/images/TTX Skenario 2.png",
        "/images/TTX Brifing 3.png",
        "/images/TTX Simulasi 4.png",
        "/images/TTX Penilian 5.png",
        "/images/TTX Evaluasi 6.png",
      ],
      flowVariant: "processGrid",
      assessmentEyebrow: "AREA PENILAIAN",
      assessmentTitle: "Apa yang Kami Nilai ?",
      assessmentText: "Ukur sejauh mana kesiapan organisasi Anda dalam menanggapi insiden siber",
      assessment: [
        { icon: "Siren", title: "Respons Insiden", text: "Evaluasi kemampuan organisasi dalam mendeteksi, merespons, dan menangani insiden siber." },
        { icon: "Gavel", title: "Pengambilan Keputusan", text: "Evaluasi kecepatan, ketepatan, dan dasar pengambilan keputusan selama latihan." },
        { icon: "MessageSquareText", title: "Komunikasi & Koordinasi", text: "Evaluasi efektivitas komunikasi dan koordinasi antar tim serta pemangku kepentingan." },
        { icon: "UsersRound", title: "Peran & Tanggung Jawab", text: "Memastikan setiap pemangku kepentingan memahami peran dan tanggung jawabnya selama respons insiden." },
        { icon: "RadioTower", title: "Eskalasi & Pelaporan", text: "Mengevaluasi mekanisme eskalasi, pelaporan, dan pemberitahuan ketika insiden berkembang." },
        { icon: "RotateCcw", title: "Kelangsungan Bisnis", text: "Menguji kesiapan organisasi dalam mempertahankan atau memulihkan operasi bisnis kritis." },
        { icon: "ClipboardCheck", title: "Kebijakan & Prosedur", text: "Mengevaluasi kesesuaian dan efektivitas SOP, Rencana Respons Insiden, dan kebijakan terkait." },
        { icon: "Landmark", title: "Manajemen Krisis", text: "Menilai kemampuan organisasi dalam mengelola situasi krisis dan dampaknya terhadap bisnis." },
      ],
      assessmentIconImages: [
        "/images/TTX Respon 8.png",
        "/images/TTX Keputusan 4.png",
        "/images/TTX Komunikasi 3.png",
        "/images/TTX Peran 6.png",
        "/images/TTX Pelaporan 1.png",
        "/images/TTX KelangsunganBisnis 2.png",
        "/images/TTX Peraturan 7.png",
        "/images/TTX SituasiKrisis 5.png",
      ],
      deliverablesEyebrow: "HASIL KERJA",
      deliverablesTitle: "Apa yang Anda Dapatkan",
      deliverablesText: "Wawasan praktis yang membantu memperkuat ketahanan siber Anda.",
      deliverables: [
        { icon: "FileCheck2", title: "Laporan Latihan", text: "Dokumentasi mengenai pelaksanaan latihan, skenario, peserta, kegiatan, dan hasil penilaian." },
        { icon: "ScanSearch", title: "Analisis Kesenjangan", text: "Identifikasi kesenjangan dan kelemahan yang terungkap selama Latihan Simulasi Meja." },
        { icon: "Gauge", title: "Evaluasi Kinerja", text: "Evaluasi respons peserta berdasarkan kriteria evaluasi yang telah ditetapkan." },
        { icon: "Eye", title: "Temuan Utama", text: "Ringkasan temuan utama yang memerlukan perhatian organisasi." },
        { icon: "RotateCcw", title: "Rekomendasi Perbaikan", text: "Rekomendasi perbaikan yang dapat digunakan untuk meningkatkan kemampuan penanggulangan insiden." },
        { icon: "ChartNoAxesCombined", title: "Ringkasan Eksekutif", text: "Ringkasan hasil latihan untuk manajemen dan para pengambil keputusan." },
        { icon: "FileCheck2", title: "Sertifikat", text: "Sertifikat partisipasi atau penyelesaian Latihan Simulasi." },
      ],
      deliverableImages: [
        "/images/TTX-Deliverables-1 laporan.png",
        "/images/TTX-Deliverables-2 analisis.png",
        "/images/TTX-Deliverables-3 evaluasi.png",
        "/images/TTX-Deliverables-4 temuan.png",
        "/images/TTX-Deliverables-5 rekomendasi.png",
        "/images/TTX-Deliverables-6 ringkasan.png",
        "/images/TTX-Deliverables-7 sertifikat.png",
      ],
      deliverablesVariant: "centeredGrid",
      packagesEyebrow: "",
      packagesTitle: "",
      packagesText: "",
      recommended: "Direkomendasikan",
      packages: [],
      audienceEyebrow: "",
      audienceTitle: "",
      audience: [],
      benefits: [],
      ctaEyebrow: "LANGKAH BERIKUTNYA",
      ctaTitle: "Siap memperkuat kesiapan siber organisasi Anda?",
      ctaButton: "Ajukan Tabletop Exercise →",
    },
    en: {
      eyebrow: "Tabletop Exercise",
      title: "Test Your Readiness Before a",
      accent: "Real Cyber Incident Happens",
      summary: "A tabletop exercise is a scenario-based simulation that helps organizations test their preparedness, coordination, and decision-making in the face of a cybersecurity incident.",
      image: "/images/tabletop-hero.png",
      imageLight: "/images/Solusi_TTX_Light.png",
      imageAlt: "Cyber crisis simulation for executives",
      heroCtaButton: "Request a Tabletop Exercise",
      heroSecondaryCtaButton: "Explore Our Scenarios",
      heroHighlights: [
        { label: "Scenario-Based", image: "/images/ttx 1.png" },
        { label: "Expert Facilitated", image: "/images/ttx 2.png" },
        { label: "Actionable Assessment", image: "/images/ttx 3.png" },
      ],
      aboutEyebrow: "TENTANG LAYANAN",
      aboutTitle: "What Is a Tabletop Exercise?",
      about: [
        "A tabletop exercise is a structured simulation designed to test how an organization responds to a cybersecurity incident.",
        "Participants are presented with incident scenarios in stages and asked to discuss the actions, decisions, communication, and coordination required at each stage of the incident.",
        "Unlike technical simulations, tabletop exercises focus on people, processes, decision-making, and coordination so that organizations can determine whether their response procedures are effective and ready for use when an incident actually occurs.",
      ],
      pillarLabel: "Simulate · Discuss · Assess · Improve",
      pillars: ["Simulate", "Discuss", "Assess", "Improve"],
      pillarImages: [
        "/images/ttx tentanglayanan1.png",
        "/images/ttx tentanglayanan2.png",
        "/images/ttx tentanglayanan3.png",
        "/images/ttx tentanglayanan4.png",
      ],
      challengesEyebrow: "MANFAAT UTAMA",
      challengesTitle: "Why Conduct a Tabletop Exercise?",
      challengesText: "Turn your incident response plan into real-world readiness.",
      challenges: [
        { icon: "BookOpenCheck", title: "Validate the Incident Response Plan", text: "Ensure that your incident response plan and procedures can be effectively implemented during an incident." },
        { icon: "Gavel", title: "Improve Decision Making", text: "Train stakeholders to make quick and accurate decisions when facing high-pressure situations." },
        { icon: "Network", title: "Strengthen Cross-Team Coordination", text: "Testing coordination among the security, IT, management, legal, communications, and relevant business unit teams." },
        { icon: "ScanSearch", title: "Identify Gaps & Weaknesses", text: "Identifying gaps in processes, communication, escalation paths, and the division of responsibilities." },
        { icon: "ShieldCheck", title: "Increase Cyber Resilience", text: "Enhancing the organization’s ability to respond to, contain, and recover from cybersecurity incidents." },
        { icon: "UsersRound", title: "Build Organizational Awareness", text: "Enhance stakeholders’ understanding of their respective roles and responsibilities during a cyber incident." },
      ],
      challengeIconImages: [
        "/images/TTX Validasi 1.png",
        "/images/TTX Keputusan 2.png",
        "/images/TTX Koordinasi 3.png",
        "/images/TTX Kesenjangan 4.png",
        "/images/TTX Ketahanan 5.png",
        "/images/TTX Kesadaran 6.png",
      ],
      featuresEyebrow: "",
      featuresTitle: "",
      features: [],
      flowEyebrow: "PROSES PELAKSANAAN",
      flowTitle: "How Our Tabletop Exercise Works",
      flowText: "From scenario preparation to actionable remediation steps.",
      flow: ["Preparation", "Scenario Design", "Briefing / Participant Preparation", "Tabletop Simulation", "Assessment", "Evaluation and Improvement"],
      flowDescriptions: [
        "We assess the organization’s needs, risk profile, environment, and objectives to design a relevant exercise.",
        "Scenarios are developed based on the organization’s needs, the threat landscape, and relevant potential cyber incidents.",
        "Participants receive a briefing on the objectives, rules, roles, and context of the scenario.",
        "The facilitator presents the scenario in stages. Participants then discuss the appropriate responses, decisions, communication, and escalation procedures.",
        "The facilitator team observes and assesses the simulation results and participants’ responses.",
        "The exercise results are analyzed to identify gaps and opportunities for improvement that can serve as a basis for enhancing cyber readiness.",
      ],
      flowImages: [
        "/images/TTX Persiapan 1.png",
        "/images/TTX Skenario 2.png",
        "/images/TTX Brifing 3.png",
        "/images/TTX Simulasi 4.png",
        "/images/TTX Penilian 5.png",
        "/images/TTX Evaluasi 6.png",
      ],
      flowVariant: "processGrid",
      assessmentEyebrow: "AREA PENILAIAN",
      assessmentTitle: "What We Assess",
      assessmentText: "Measure how prepared your organization is to respond to a cyber incident.",
      assessment: [
        { icon: "Siren", title: "Incident Response", text: "Evaluate the organization’s ability to detect, respond to, and handle cyber incidents." },
        { icon: "Gavel", title: "Decision Making", text: "Evaluate the speed, accuracy, and basis of decision-making during the exercise." },
        { icon: "MessageSquareText", title: "Communication & Coordination", text: "Evaluate the effectiveness of communication and coordination among teams and stakeholders." },
        { icon: "UsersRound", title: "Roles & Responsibilities", text: "Ensure that every stakeholder understands their roles and responsibilities during an incident response." },
        { icon: "RadioTower", title: "Escalation & Reporting", text: "Evaluate escalation, reporting, and notification mechanisms as an incident unfolds." },
        { icon: "RotateCcw", title: "Business Continuity", text: "Test the organization’s readiness to maintain or restore critical business operations." },
        { icon: "ClipboardCheck", title: "Policies & Procedures", text: "Evaluate the appropriateness and effectiveness of SOPs, the Incident Response Plan, and related policies." },
        { icon: "Landmark", title: "Crisis Management", text: "Assessing an organization’s ability to manage crisis situations and their impact on the business." },
      ],
      assessmentIconImages: [
        "/images/TTX Respon 8.png",
        "/images/TTX Keputusan 4.png",
        "/images/TTX Komunikasi 3.png",
        "/images/TTX Peran 6.png",
        "/images/TTX Pelaporan 1.png",
        "/images/TTX KelangsunganBisnis 2.png",
        "/images/TTX Peraturan 7.png",
        "/images/TTX SituasiKrisis 5.png",
      ],
      deliverablesEyebrow: "HASIL KERJA",
      deliverablesTitle: "What You Get",
      deliverablesText: "Actionable insights that help strengthen your cyber resilience.",
      deliverables: [
        { icon: "FileCheck2", title: "Exercise Report", text: "Documentation of the exercise implementation, scenarios, participants, activities, and assessment results." },
        { icon: "ScanSearch", title: "Gap Analysis", text: "Identification of gaps and weaknesses discovered during the Tabletop Simulation Exercise." },
        { icon: "Gauge", title: "Performance Evaluation", text: "Evaluation of participants’ responses based on established evaluation criteria." },
        { icon: "Eye", title: "Key Findings", text: "A summary of key findings that require the organization’s attention." },
        { icon: "RotateCcw", title: "Recommendations for Improvement", text: "Recommendations for improvement that can be used to enhance incident response capabilities." },
        { icon: "ChartNoAxesCombined", title: "Executive Summary", text: "A summary of the exercise results for management and decision-makers." },
        { icon: "FileCheck2", title: "Certificate", text: "A certificate of participation or completion of the Tabletop Exercise." },
      ],
      deliverableImages: [
        "/images/TTX-Deliverables-1 laporan.png",
        "/images/TTX-Deliverables-2 analisis.png",
        "/images/TTX-Deliverables-3 evaluasi.png",
        "/images/TTX-Deliverables-4 temuan.png",
        "/images/TTX-Deliverables-5 rekomendasi.png",
        "/images/TTX-Deliverables-6 ringkasan.png",
        "/images/TTX-Deliverables-7 sertifikat.png",
      ],
      deliverablesVariant: "centeredGrid",
      packagesEyebrow: "",
      packagesTitle: "",
      packagesText: "",
      recommended: "Recommended",
      packages: [],
      audienceEyebrow: "",
      audienceTitle: "",
      audience: [],
      benefits: [],
      ctaEyebrow: "LANGKAH BERIKUTNYA",
      ctaTitle: "Ready to strengthen your organization's cyber readiness?",
      ctaButton: "Request a Tabletop Exercise →",
    },
  }} />;
}
